<a href="https://colab.research.google.com/github/ragabsayed63502/Ai_assignment-/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise 1: Create a 4X2 integer array and Prints its attributes

In [ ]:
import numpy as np
arr = np.empty([4,2], dtype = np.uint16) 
print(arr)
print("Attributes")
print("1): Array Shape is: ", arr.shape)
print("2): dimensions are ", arr.ndim)
print("3): each element of array in bytes is ", arr.itemsize)

[[4128  457]
 [   0    0]
 [   0    0]
 [   1    0]]
Attributes
1): Array Shape is:  (4, 2)
2): dimensions are  2
3): each element of array in bytes is  2


#Exercise 2: Create a 5X2 integer array from a range between 100
#to 200 such that the difference between each element is 10

In [ ]:
import numpy as np
arr = np.arange( 100 , 200, 10 )
arr = arr.reshape(5,2)
print (arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


#Exercise 3: Following is the provided numPy array. Return array of
#items by taking the third column from all rows


In [ ]:
import numpy as np
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(arr[0][2],arr[1][2],arr[2][2])

33 66 99


#Exercise 4: Return array of odd rows and even columns from
#below numpy array

In [ ]:
import numpy as np
arr = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(arr[::2 , 1::2])# start from 0 in even and add 2 ,start from 1 in even and add 2 


[[ 6 12]
 [30 36]
 [54 60]]


#Exercise 5: Create a result array by adding the following #two 
#NumPy arrays. Next, modify the result array by calculating #the square of each element

In [ ]:
import numpy as np
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
newarr = arrayOne+arrayTwo;
print(newarr)

for num in np.nditer(newarr, op_flags = ['readwrite']):
   num[...] = num*num

print('square root')
print(newarr)     

[[20 39 33]
 [25 25 28]]
square root
[[ 400 1521 1089]
 [ 625  625  784]]


##pandas
##Exercise 1: Clean the dataset and update the CSV file?

In [ ]:
import pandas as pd
df = pd.read_csv('/content/covid19.csv',na_values={
'Country,Other':["?","n.a","NaN"],
'TotalCases':["?","n.a","NaN"],
'NewCases':["?","n.a","NaN"],
'TotalDeaths':["?","n.a","NaN"]})
print(df.head(5))

   Unnamed: 0 Country,Other  TotalCases NewCases TotalDeaths
0           0           USA  29,383,324  +12,619    529,515 
1           1         India  11,156,250  +16,927    157,471 
2           2        Brazil  10,647,845      NaN    257,562 
3           3        Russia   4,278,750  +10,535     87,348 
4           4            UK   4,188,400      NaN    123,296 


#Exercise 2: Find the most expensive car company name?
#Print most expensive car’s company name and price

In [ ]:
import pandas as pd
df = pd.read_csv(".....")
df = df [['company','price']][df.price==df['price'].max()]
print(df)

#Exercise 3: Print All Toyota Cars details?

In [ ]:
import pandas as pd
df = pd.read_csv("..")
carManuf = df.groupby('company')
toyota = carManuf.get_group('toyota')
print(toyota)

#Exercise 4: Count total cars per company?

In [ ]:
import pandas as pd
df = pd.read_csv("...")
df['company'].value_counts()

#Exercise 6: Find each company’s Higesht price car?

In [ ]:
import pandas as pd
df = pd.read_csv("...")
carManuf = df.groupby('company')
price = carManuf['company','price'].max()
print(price)