<a href="https://colab.research.google.com/github/ragabsayed63502/Ai_assignment-/blob/main/Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Task 1
#Task 2

In [ ]:
import pandas as pd
df = pd.read_csv('/content/ds_salaries.csv')
x = df['salary'].mean() #average values
df.sort_values(by = 'salary')
print(x)
print(df.head(5))

324000.0626029654
   Unnamed: 0  work_year experience_level employment_type  \
0           0       2020               MI              FT   
1           1       2020               SE              FT   
2           2       2020               SE              FT   
3           3       2020               MI              FT   
4           4       2020               SE              FT   

                    job_title  salary salary_currency  salary_in_usd  \
0              Data Scientist   70000             EUR          79833   
1  Machine Learning Scientist  260000             USD         260000   
2           Big Data Engineer   85000             GBP         109024   
3        Product Data Analyst   20000             USD          20000   
4   Machine Learning Engineer  150000             USD         150000   

  employee_residence  remote_ratio company_location company_size  
0                 DE             0               DE            L  
1                 JP             0              

#Task 3: Create two data frames using the following two
#Dicts, Merge two data frames, and append the second
#data frame as a new column to the first data frame.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/ds_salaries.csv')
c = pd.read_csv('/content/ds_salaries.csv')
newc = df.merge(c,on = 'Unnamed: 0')

newc.head(5)


Unnamed: 0  work_year_x experience_level_x employment_type_x  \
0           0         2020                 MI                FT   
1           1         2020                 SE                FT   
2           2         2020                 SE                FT   
3           3         2020                 MI                FT   
4           4         2020                 SE                FT   

                  job_title_x  salary_x salary_currency_x  salary_in_usd_x  \
0              Data Scientist     70000               EUR            79833   
1  Machine Learning Scientist    260000               USD           260000   
2           Big Data Engineer     85000               GBP           109024   
3        Product Data Analyst     20000               USD            20000   
4   Machine Learning Engineer    150000               USD           150000   

  employee_residence_x  remote_ratio_x  ... experience_level_y  \
0                   DE               0  ...                 MI   
1                   JP               0  ...                 SE   
2                   GB              50  ...                 SE   
3                   HN               0  ...                 MI   
4                   US              50  ...                 SE   

  employment_type_y                 job_title_y salary_y salary_currency_y  \
0                FT              Data Scientist    70000               EUR   
1                FT  Machine Learning Scientist   260000               USD   
2                FT           Big Data Engineer    85000               GBP   
3                FT        Product Data Analyst    20000               USD   
4                FT   Machine Learning Engineer   150000               USD   

  salary_in_usd_y  employee_residence_y remote_ratio_y  company_location_y  \
0           79833                    DE              0                  DE   
1          260000                    JP              0                  JP   
2          109024                    GB             50                  GB   
3           20000                    HN              0                  HN   
4          150000                    US             50                  US   

  company_size_y  
0              L  
1              S  
2              M  
3              S  
4              L  

[5 rows x 23 columns]

#Numpy
#Task 1: Split the array into four equal-sized sub-arrays

In [ ]:
import numpy as np
a = np.arange(10,34,1).reshape((8,3))
subarr = np.array_split(a, 4)
print(subarr)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


#Task 2: Sort following NumPy array
# Case 1: Sort array by the second row
# Case 2: Sort the array by the second column

In [ ]:
import numpy as np
sampleArray =np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

print('~~~~~~~~~~~~~')

a1 = sampleArray[ : , sampleArray[ 1 , : ].argsort()]
print('sort by Row:\n',a1)
print('~~~~~~~~~~~~~')

a2 = sampleArray[sampleArray[ : , 1].argsort()]
print('sort by Column:\n' ,a2)


[[34 43 73]
 [82 22 12]
 [53 94 66]]
~~~~~~~~~~~~~
sort by Row:
 [[73 43 34]
 [12 22 82]
 [66 94 53]]
~~~~~~~~~~~~~
sort by Column:
 [[82 22 12]
 [34 43 73]
 [53 94 66]]


#Task 3:Print max from axis 0 and min from axis 1 from the
#following 2-D array.

In [ ]:
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

print('max\n',np.max(sampleArray , axis=0))

print('\nmin\n',np.min(sampleArray,axis=1))

max
 [82 94 73]

min
 [34 12 53]


#Task 4: Delete the second column from a given array and
#insert the following new column in its place.

In [ ]:
from os import spawnlp
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print('array\n\n',sampleArray)

sampleArray = np.delete( sampleArray , 1,axis=1)
print('\n\nafter delete \n',sampleArray)
sampleArray = np.insert(sampleArray , 1, newColumn , axis=1,)
print('\n\nafter Add column \n',sampleArray)

#newColumn = np.add(newColumn , sampleArray , axis = 0)

array

 [[34 43 73]
 [82 22 12]
 [53 94 66]]


after delete 
 [[34 73]
 [82 12]
 [53 66]]


after Add column 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]
